apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom
  namespace: monitoring
  labels:
    app: prom
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: prometheus
        image: aftab70/prometheus:latest
        args:
          - '--storage.tsdb.retention=6h'
          - '--storage.tsdb.path=/prometheus'
          - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: prom
          containerPort: 9090
      restartPolicy: Always
